#!/bin/sh
days="Today\nTomorrow\nYesterday\nCreate"
day=$(printf "$days" | dmenu -c -bw 2 -i -p "Calender" -g 1 -l 10)
if [ "$day" ]; then	
	if [ "$day" = "Create" ]; then
		dayIndex=$(printf "" | dmenu -c -bw 2 -i -p "Day" -g 1 -l 1)
		if [ "$dayIndex" ]; then
		 	echo "$(habbit create ~/Dev/Write/daily "$dayIndex" | dmenu -i -c -bw 2 -p "Result" -g 1 -l 10)"
		fi
	else
		case "$day" in
			*Today) dayIndex="0";;
			*Tomorrow) dayIndex="+1";;
			*Yesterday) dayIndex="-1";;
		esac
		title=$(habbit list ~/Dev/Write/daily "$dayIndex" | dmenu -c -bw 2 -i -p "Agendas" -g 1 -l 10) 
		if [ "$title" ]; then
			text=$(habbit fetch ~/Dev/Write/daily "$dayIndex" "$title")
			yad --info --back="blue" --margins=20 --text="$text" --no-buttons --width=500 --text-width=113
		fi
	fi
fi
