#!/bin/sh
choice=$(buku --np --nc -r "." -f 5| tr '\t' '.' | dmenu -l 16 -g 1 -p Bookmarks -i -bw 2 -c -cw 600)
if [ "$choice" ]; then
	bookmark_id=$(echo "$choice" | awk -F '.' '{print $1}')
	bookmark=$(buku --np --nc -f 10 -p "$bookmark_id")
	ANS=$(printf "QuteBrowser\nChromium\nFirefox\nDelete" | dmenu -p Browser -i)
	echo "$bookmark_id"
	echo "$bookmark"
	echo "$browser_choice"
	case "$ANS" in
		QuteBrowser) qutebrowser "$bookmark" --target tab;;
		Chromium) chromium "$bookmark";;
		Firefox) firefox --new-tab "$bookmark";;
		Delete) buku -d "$bookmark_id" --tacit;;
	esac
fi
