#!/bin/sh
ANS=$(echo "|||累|襤" | \
                rofi -sep "|" -dmenu -i -p '' "" -width 20 \
                -hide-scrollbar -eh 1 -line-padding 4 -padding 50 -lines 4 -theme "exit")
            case "$ANS" in
                *) dm-tool lock;;
		*) systemctl hibernate;;
		*) awesome-client "awesome.quit()"; fluxbox-remote "exit"; pkill dwm; qshell -c "shutdown()";;
                *累) systemctl reboot ;;
                *襤) systemctl poweroff
            esac
