#!/bin/sh
ANS=$(echo "Lock|Hibernate|Logout|Reboot|Shutdown" | \
                rofi -sep "|" -dmenu -i -p '' "" -width 20 \
                -hide-scrollbar -eh 1 -line-padding 4 -padding 50 -lines 4 -theme "exit")
            case "$ANS" in
                *Lock) dm-tool lock;;
		*Hibernate) systemctl hibernate;;
		*Logout) pkill dwm; pkill xmonad; pkill bspx; pkill feather_wm;openbox --exit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl poweroff ;;
            esac
