#!/bin/sh
if [ "$1" ]; then
	CP_FILE=$($1)
	if [ "$CP_FILE" ]; then
		ANS=$(fd -t d | fzf --preview 'bat --color=always --style=header,grid --line-range :300 {}')
		if [ "$ANS" ]; then
			if [ "$CP_FILE" ]; then
	      			cp "$CP_FILE" "$ANS"
			fi
		fi
	fi
fi
