#!/bin/sh
if [ "$1" ]; then
	MENU_COMMAND="dmenu -i -l 10 -g 1 -p Flutter"
else
	MENU_COMMAND="fzf --prompt=Command"
fi
ANS=$(cat "$HOME/scripts/fzf/f_commands.txt" | awk -F ':' '{print $1}' | $MENU_COMMAND) 
if [ "$ANS" ]; then
	COMMAND=$(cat "$HOME/scripts/fzf/f_commands.txt" | rg "$ANS" | awk -F ':' '{print $2}') 
	$COMMAND
fi
