#!/bin/zsh 
cmd=$(echo "Emacs Client|Emacs Daemon|Kill Server" | \
                rofi -sep "|" -dmenu -i -p '' "" -width 20 \
                -hide-scrollbar -eh 1 -line-padding 4 -padding 50 -lines 4 -theme "emacs")
if [ "$cmd" ]; then	
	if [ "$cmd" = "Emacs Client" ]; then
	    emacsclient -c &
	elif [ "$cmd" = "Emacs Daemon" ]; then
	    emacs --daemon &
	elif [ "$cmd" = "Kill Server" ]; then
	    pkill emacs
	fi
fi
