#!/bin/sh
arg=$(echo "" |dmenu -h 20 -fn 'monospace 10' -nb "#231F20" -nf "#BA8866" -sb "#BA8866" -sf "#231F20" -p Calculate) 
if [ "$arg" ]; then
	result=$(calc "$arg" | tr -d "\t")
	echo "$result" | dmenu -p "Answer"
fi
