#!/bin/sh 
battery="/sys/class/power_supply/BAT0/"
capacity=$(cat "$battery"/capacity)
bstatus=$(cat "$battery"/status)
icon=""
if [ "$bstatus" = "Charging" ]; then
	icon=""
fi
echo "  $icon  $capacity% "
