#!/bin/sh
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu2_run
else
	cache=$HOME/.dmenu2_cache # if no xdg dir, fall back to dotfile in ~
fi
(
	IFS=:
	if stest -dqr -n "$cache" $PATH; then
		stest -flx $PATH | sort -u | tee "$cache" | dmenu2 "$@"
	else
		dmenu2 "$@" < "$cache"
	fi
) | ${SHELL:-"/bin/sh"} &
